### ISSUE TITLE
enchant unsafe

### ISSUE THREAD

**Issue by TOWUK** [YouHaveTrouble/ServerBasics#7]
please add basic unsafe enchants like set all type enchant on all type item

**Comment by YouHaveTrouble** [comment]
Added in [1.3](https://github.com/YouHaveTrouble/ServerBasics/releases/tag/1.3-alpha)

**Comment by TOWUK** [comment]
> Added in [1.3](https://github.com/YouHaveTrouble/ServerBasics/releases/tag/1.3-alpha)

great! <3
